[package]
name = "cinrust"
version = "0.1.0"
authors = ["Niels Bross <niels@glitchheart.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cty = "0.2.1"
libc = "0.2.0"

